import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MY PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <h1>Portfolio</h1>
      </main>
    </div>
  )
}
